### ISSUE TITLE
Language change should probably lead to the same page

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#10]
I guess there should be a simple way to avoid being redirected to the home page of the documentation site when changing the language. And maybe it should be implemented, as it doesn't seem to be a rare case when a user comes to the English version of the site via a link or search engine results and then realises there's a translated version in her native language, clicking on the flag... and being moved away from the original stuff she was looking for.

**Comment by alexchopin** [comment]
Hi, that's true. It'll be fixed soon.

**Comment by Atinux** [comment]
It's now online @gbezyuk 

https://ru.nuxtjs.org/
