### ISSUE TITLE
official docs site javascript load error

### ISSUE THREAD

**Issue by falstack** [nuxt/docs#1028]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/16357724/49624535-c1a27080-fa0c-11e8-8da4-92b8bf782d38.png)

### What is expected ?

because CDN?

### What is actually happening?

axios module load error, page can not switch

### Additional comments?

I don't know where i can report it,  i can't visit `https://discordapp.com/invite/HtAAAQa` too, sorry close this issue, and change CDN provider, thanks

**Comment by manniL** [comment]
Can't reproduce.
