### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by dimensi0n** [nuxt/docs#1064]
### Reproduction link

[https://github.com/nuxt-community/modules](https://github.com/nuxt-community/modules)

### Steps to reproduce

Read the README.md

### What is expected ?

List of all the modules

### What is actually happening?

Broken link to a firebase package which does not exist

### Additional comments?

I can open a pull request if you want

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c149">#c149</a>)</em></sub></div>

**Comment by manniL** [comment]
@dimensi0n Please open a PR, yes :relaxed: 

PS: This is the `docs` repo. This issue should better belong into the linked `modules` repo.
