### ISSUE TITLE
ExtendRoutes documentation

### ISSUE THREAD

**Issue by alexchopin** [nuxt/docs#113]
Related to https://github.com/nuxt/nuxt.js/issues/641

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c22">#c22</a>)</em></sub></div>

**Comment by Sabbir-Noire** [comment]
I have to use `alias` url in my project but couldn't implement it and was misled by the documentation as it was written that `The schema of the route should respect the vue-router schema.`. But you can't use the vue-router `alias`.

I think the wording could be improved. Any suggestion to what to write in the #extendroutes  section to make it better ?

https://nuxtjs.org/api/configuration-router/#extendroutes

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
