### ISSUE TITLE
Document extensions

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#1156]
Document `extensions`

_Originally posted by @manniL in https://github.com/nuxt/docs/issues/1075#issuecomment-460978141_

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
