### ISSUE TITLE
Event handling / component communication

### ISSUE THREAD

**Issue by maluio** [nuxt/docs#1159]
### What problem does this feature solve?

My use case was:
A button in a parent component triggers a method call in a child component. 

I couldn't find a solution in the nuxtjs docs. Eventually, I stumbled upon this thread:
https://github.com/nuxt/nuxt.js/issues/849

Using
```
this.$root.$emit
this.$root.$on
```
solved my problem.

### What does the proposed changes look like?

Ideally,  a new page explains the available options for component communication: (this.$root.$emit, eventBus, ...)

The new page could be available at https://nuxtjs.org/api/component-communiction 

If this is a valid feature request I could write that page.

Thank you.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c178">#c178</a>)</em></sub></div>

**Comment by manniL** [comment]
Strongly personal suggestion: We have `Vuex` for state management. I highly recommend to **avoid** something an **event bus**.

>  A button in a parent component triggers a method call in a child component.
You can then pass down the event from the parent component ☺️ 

As this topic is more related to Vue (https://vuejs.org/v2/guide/events.html#ad) I'll close here.
Thanks anyway for the idea 👍
