### ISSUE TITLE
Live demo button is not working in middleware demo page.

### ISSUE THREAD

**Issue by jicjjang** [nuxt/docs#116]
middleware demo page is not working when I click the live demo button in `https://nuxtjs.org/examples/middleware/` url.

Please check about it :)

**Comment by alexchopin** [comment]
Thanks for the report, I will work on it 👍

**Comment by jicjjang** [comment]
Additionally, Not working [This method is made for test purposes](https://nuxtjs.org/api/nuxt-render-and-get-window/guide/development-tools#end-to-end-testing) link from [API: nuxt.renderAndGetWindow(url, options)](API: nuxt.renderAndGetWindow(url, options)) page.
