### ISSUE TITLE
Documentation Request vuex-store.md

### ISSUE THREAD

**Issue by SumNeuron** [nuxt/docs#1168]
The vuex store documentation needs to be extended to give more clear specification on more complex store structures.

e.g. 

```
store/
--state.js
--actions.js
--getters.js
--mutations.js
--index.js
--modules/
--+--moduleA/
--+--+--state.js
--+--+--actions.js
--+--+--getters.js
--+--+--mutations.js
--+--+--index.js
--+--moduleB/
--+--+--state.js
--+--+--actions.js
--+--+--getters.js
--+--+--mutations.js
--+--+--index.js

```

currently as it stands it states:

>You can optionally break down a module file into separate files: state.js, actions.js, mutations.js and getters.js. If you maintain an index.js file with state, getters and mutations while having a single separate file for actions, that will also still be properly recognized.

which is fine if your store has no modules.
but it doesnt clarify how to arrange this for multiple modules.

In addition, for the "classic mode" which will be deprecate in v3

there is no documentation for what the index file should be:

here is an example from my project
```
import Vuex from 'vuex'

import mutations from '@/store/mutations.js';
import actions from '@/store/actions.js';
import getters from '@/store/getters.js';
import state from '@/store/state.js';

const createStore = () => {
  const store = new Vuex.Store({
    namespaced: true,
    state,
    actions,
    getters,
    mutations,
    modules: {}
  })

  return store
}

export default createStore
 ```

so all this information should be provided

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c181">#c181</a>)</em></sub></div>

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
