### ISSUE TITLE
File edit link should lead to a correct github repo depending on the translation

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#12]
For Russian docs somehow we need to lead people to TG translation repo, not the primary one at nuxt/docs when they've caught a typo.
<img width="1369" alt="screen shot 2017-01-12 at 15 11 45" src="https://cloud.githubusercontent.com/assets/1452165/21889337/83143b06-d8d9-11e6-8d20-41afabf7a453.png">

**Comment by Atinux** [comment]
Fixed, you can check https://ru.nuxtjs.org/guide/

**Comment by gbezyuk** [comment]
awesome, thank you!
