### ISSUE TITLE
[nodemon] app crashed after run command of  ’npm run dev’

### ISSUE THREAD

**Issue by JKChen** [nuxt/docs#123]
My node is v7.10.0

**Comment by pi0** [comment]
Please provide more information. What is your nodemon output log?

**Comment by JKChen** [comment]
package.json:
`"dev": "nodemon --watch *.js --exec 'node --harmony api.js'",`
change to:
`"dev": "nodemon --watch *.js -x npm run start",`

and then ‘npm run dev’ start a dev serve normally.

**Comment by JKChen** [comment]
Thank u for your reply·

**Comment by Atinux** [comment]
Fixed, thanks @JKChen

**Comment by jason65** [comment]
visit  localhost:4000 only show  File not found,
what is wrong?

**Comment by jason65** [comment]
actually ,i still do not kown how to run this project .

**Comment by farzadso** [comment]
@jason65 Try using `npm run nuxt` or `yarn nuxt`
