### ISSUE TITLE
ja: some words aren't italic

### ISSUE THREAD

**Issue by JohnTitor** [nuxt/docs#1268]
### Version

[2.3.X](https://github.com/docs/releases/tag/2.3.X)

### Reproduction link

[https://ja.nuxtjs.org/faq/netlify-deployment/](https://ja.nuxtjs.org/faq/netlify-deployment/)

### Steps to reproduce

See https://ja.nuxtjs.org/faq/netlify-deployment/

### What is expected ?

Specific words are italic correctly.

![DeepinScreenshot_select-area_20190325020904.png](https://cmty.s3.eu-west-1.amazonaws.com/74384145/90015b00-4e57-11e9-a06f-a17a24da0884.png)

### What is actually happening?

Some words aren't italic, e.g.  `*"New site from Git"*`

![DeepinScreenshot_select-area_20190325020852.png](https://cmty.s3.eu-west-1.amazonaws.com/74384145/95828130-4e57-11e9-a06f-a17a24da0884.png)

### Additional comments?

This will be fixed by using underscores like the other languages' documentation but it seems that asterisks are used in Japanese documentation. If the work is just to replace  `*` with `_`, I can open a PR.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c186">#c186</a>)</em></sub></div>

**Comment by inouetakuya** [comment]
Thank you for your report!!

> If the work is just to replace * with _, I can open a PR.

Thank you, please. 😄
