### ISSUE TITLE
Faq page only show How to use external resources

### ISSUE THREAD

**Issue by pablocattaneo** [nuxt/docs#1278]
### Reproduction link

[https://nuxtjs.org/faq](https://nuxtjs.org/faq)

### Steps to reproduce

Go into https://nuxtjs.org/faq

### What is expected ?

See all this content:

https://github.com/nuxt/docs/tree/master/en/faq

### What is actually happening?
The only content show in https://nuxtjs.org/faq is https://github.com/nuxt/docs/blob/master/en/faq/external-resources.md
![CopyQ.kn1412.png](https://cmty.s3.eu-west-1.amazonaws.com/74384145/f716c130-50bf-11e9-b24f-9b8890408f45.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c189">#c189</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @pablocattaneo 

Thank you for the report.

Actually, it just show the first page of the listing (left panel).

We will improve this in the next docs to show the list by default. Thanks!

**Comment by pablocattaneo** [comment]
Hi @Atinux !. Thanks you for collaborate in the Nuxt documentation!
Oh you are right!  here is the list of content!.I think that is a good idea the improvement that you propose, because in this moment is the list is a little hide to my resolution: 1366x768
![faq-nuxt](https://user-images.githubusercontent.com/11772956/55156476-c82e3280-5138-11e9-979a-35adcab80bab.png)

I think the change you propose also is going to improve the url, right now is confuse: in https://nuxtjs.org/faq I supposed to find a list of content (or the completed content) and find and specific content in his own url like happen  with https://nuxtjs.org/faq/pre-processors

Regards!

**Comment by pablocattaneo** [comment]
> Hi @Atinux !. Thanks you for collaborate in the Nuxt documentation!

@Atinux  I noticed that you are the creator of Nuxt and I only gave you thanks for collaborate in the documentation!! :yum: . Thank you for this great framework Sébastien!! Keep going! :muscle:
