### ISSUE TITLE
Improve build.extends explanation / examples

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#1295]
https://nuxtjs.org/faq/extend-webpack/ isn't very helpful.

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
