### ISSUE TITLE
duplicated items in official website

### ISSUE THREAD

**Issue by iamwelk** [nuxt/docs#1307]
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues/5496](https://github.com/nuxt/nuxt.js/issues/5496)

### Steps to reproduce

https://user-images.githubusercontent.com/6983075/55786466-e1df5a80-5ae6-11e9-8c3e-74134c0130a7.png

### What is expected ?

remove the duplicated item

### What is actually happening?

duplicated items

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9023">#c9023</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Fixed in https://github.com/nuxt/docs/commit/b21810886260ff5451b4ce2bd34cf2c4675811ec
