### ISSUE TITLE
Mention serverMiddleware uses router's base

### ISSUE THREAD

**Issue by xxRockOnxx** [nuxt/docs#1332]
### What problem does this feature solve?

I was confused why my serverMiddleware only to find out after a couple of experimentation that it would only work if I prepend the router's base path.

I thought serverMiddleware was called before everything else including router's configuration but it wasn't.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c193">#c193</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. It is intended default behavior. Because the serverMiddleware is mainly for extending SSR behavior.

You can set `prefix: false` to disable it:

```js
export default {
   path: '/test',
   prefix: false,
   handler: (req, res) => {

   }
}
```

**Comment by xxRockOnxx** [comment]
I see. It's nice I don't have to rely on `connect` and `http` anymore. Is the `prefix` option mentioned somewhere in the docs then, @pi0 ?

**Comment by pi0** [comment]
@xxRockOnxx I think no but if interested i can reopen and transfer issue to the docs to be added.

**Comment by pi0** [comment]
@xxRockOnxx Sorry you are right. I tough issue is on `nuxt.js` repository.

**Comment by manniL** [comment]
@xxRockOnxx it is here: https://nuxtjs.org/api/configuration-render#static

However, no mention of serverMiddleware. Would you send in a PR? :relaxed:
