### ISSUE TITLE
Broken Link https://nuxtjs.org/faq/google-analytics

### ISSUE THREAD

**Issue by rstormsf** [nuxt/docs#1353]
### Version

[2](https://github.com/docs/releases/tag/2)

### Reproduction link

[https://nuxtjs.org/faq/google-analytics](https://nuxtjs.org/faq/google-analytics)

### Steps to reproduce

Go to https://nuxtjs.org/faq/google-analytics

### What is expected ?

Success ( 200) 

### What is actually happening?

500 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c201">#c201</a>)</em></sub></div>

**Comment by manniL** [comment]
For me the page is up 🤔

**Comment by rstormsf** [comment]
I agree it's fixed now.
