### ISSUE TITLE
configuration-build pages do not load

### ISSUE THREAD

**Issue by Anaphase** [nuxt/docs#1404]
### Version

[latest](https://github.com/docs/releases/tag/latest)

### Reproduction link

[https://nuxtjs.org/api/configuration-build](https://nuxtjs.org/api/configuration-build)

### Steps to reproduce

Try to load https://nuxtjs.org/api/configuration-build (or any of the anchor tags on that page.)

### What is expected ?

The page should load the configuration-build docs.

### What is actually happening?

The page does not load, instead showing a 404 error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c204">#c204</a>)</em></sub></div>

**Comment by Atinux** [comment]
Fixed thank you!
