### ISSUE TITLE
Unexpected type of Vue Router component in TypeScript

### ISSUE THREAD

**Issue by MasterHiei** [nuxt/docs#1435]
### Version

[VERSION 2.8.X](https://github.com/docs/releases/tag/VERSION 2.8.X)

### Reproduction link

[https://nuxtjs.org/api/configuration-router#extendroutes](https://nuxtjs.org/api/configuration-router#extendroutes)

### Steps to reproduce

Adding a custom route in `nuxt.config.js` like below:
```javascript
export default {
  router: {
    extendRoutes (routes, resolve) {
      routes.push({
        name: 'custom',
        path: '*',
        component: resolve(__dirname, 'pages/404.vue')
      })
    }
  }
}
```

### What is expected ?

pass without error

### What is actually happening?

Get a type error.
```
Type 'string' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> | VueConstructor<Vue> | AsyncComponentPromise<...> | AsyncComponentFactory<...> | undefined'.ts(2322)
router.d.ts(77, 3): The expected type comes from property 'component' which is declared here on type 'NuxtRouteConfig'
```

### Additional comments?

Is it a bug of TypeScript type definitions?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c209">#c209</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@MasterHiei Yes it's a bug, that should have been fixed by https://github.com/nuxt/nuxt.js/pull/5841 but will only be shipped in next Nuxt release.

I'm working on externalizing TypeScript support & types, so we won't be depending on Nuxt releases to fix or improve types.
