### ISSUE TITLE
子视图无法异步获取数据

### ISSUE THREAD

**Issue by caizhisheng** [nuxt/docs#147]
路由绑定的页面组件?  请问这句话怎么理解？

**Comment by alexchopin** [comment]
@ausir0726

**Comment by caizhisheng** [comment]
@alexchopin  ok thx 
and l has another question: 
  l want to use function in asyncData ,what can I do?
  for example: 

![12345](https://user-images.githubusercontent.com/13362401/27174746-bca17be2-51ef-11e7-8760-9c1484b8cfe2.png)

**Comment by alexchopin** [comment]
Hi,
You cannot, in your case you should use computed property to get `todayLoanAmount` parse and formatted.
