### ISSUE TITLE
"Unit Testing" describes End to End testing, not unit testing

### ISSUE THREAD

**Issue by samtgarson** [nuxt/docs#15]
[This page](https://nuxtjs.org/guide/unit-testing) is titled Unit Testing but describes e2e testing:

> Ava is a powerful JavaScript testing framework, mixed with jsdom, we can use them to do end-to-end testing easily.

I'm struggling to setup unit testing of my components, I'm currently using [ava-webpack](https://github.com/thrandre/ava-webpack) but this library removes some of the good stuff that comes with AVA.

Have you had any experience unit testing components in a Nuxt app? Cheers

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c5">#c5</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @samtgarson 

Thank you for spotting it, it's updated: https://nuxtjs.org/guide/tests

I did not work on unit testing yet for Nuxt application but I will give a try with Karma.

**Comment by samtgarson** [comment]
👍

**Comment by blowsie** [comment]
Is this still relevant in the latest version? 
There is come examples already https://nuxtjs.org/examples/testing
I think this can be closed?+
