### ISSUE TITLE
1.x docs

### ISSUE THREAD

**Issue by pi0** [nuxt/docs#152]
Here is a quick checklist keeping track of all needed changes. (WIP)
https://github.com/nuxt/docs/tree/1.0

# API

## Configuration
- [x] Build
  - [x] Deprecate Loaders
  - [x] extractCSS
  - [x] watch
- [x] serverMiddleware
- [x] Modules
- [ ] cache ~> render.ssr
- [x] Deprecate performance
- [ ] Render
 - [ ] SSR
 - [ ] resourceHints
 - [ ] http2
 - [ ] etag
 - [ ] cache ?
- [x] Update Menu

## Nuxt
 - [ ] render

# Guide
- [x] Writing Modules
- [ ] Configuration
- [ ] Update & Copy contribution guide into nuxt.js repo
- [ ] Update Vue-CLI
- [ ] * Plugins for new SSR system
- [ ] (optional) Some best practices for new SSR & global context

**Comment by Atinux** [comment]
@pi0 no need to talk about `nuxtAppDir` right now.

For cache -> `render.ssr.cache`
