### ISSUE TITLE
Link to packages/vue-app/template/router.scrollBehavior.js doesn't work

### ISSUE THREAD

**Issue by thrazu** [nuxt/docs#1542]
In documentation, the link to https://github.com/nuxt/nuxt.js/blob/feat/dev/packages/vue-app/template/router.scrollBehavior.js doesn't work. It returns 404

**Comment by manniL** [comment]
@thrazu 	Could you show me the page where it was linked?

**Comment by Nojusle** [comment]
I can, you can found it [here](https://nuxtjs.org/api/configuration-router#scrollBehavior)
