### ISSUE TITLE
Document new vueMeta config key

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#1626]
Document https://github.com/nuxt/nuxt.js/pull/6432

**Comment by rkpattnaik780** [comment]
Hello, I have recently started using nuxt. I came across this issue and want to contribute. Can I get some leads to get started.

**Comment by manniL** [comment]
@rkpattnaik780 Hey 👋 

The linked PR is not documented and should be a separate page like https://nuxtjs.org/api/configuration-cli for example ☺️

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
