### ISSUE TITLE
Document `addMeta` CSP value

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#1655]
Document https://github.com/nuxt/nuxt.js/pull/5354

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
