### ISSUE TITLE
English docs could use some improvement--would like to help

### ISSUE THREAD

**Issue by Jutanium** [nuxt/docs#173]
Hi,
Most of the english docs could use some editing/rewriting to make them read like native English. There's a good number of grammar mistakes and awkward word choices and sentence structures.

I'd love to help, but I'm new to open source. Do I just fork this project and start editing? Do I do a PR after each page?

**Comment by Atinux** [comment]
Hi @Jutanium 

You can use GitLocalize to help us easily: https://gitlocalize.com/repo/100/en

We're more than happy to have your help on English docs!
