### ISSUE TITLE
[FR] Routing menu issue (named views)

### ISSUE THREAD

**Issue by Woosy** [nuxt/docs#1765]
### Version

[master](https://github.com/docs/releases/tag/master)

### Reproduction link

[https://fr.nuxtjs.org/guide/routing#named-views](https://fr.nuxtjs.org/guide/routing#named-views)

### Steps to reproduce

Go to https://fr.nuxtjs.org/guide/routing#named-views
Open "Routage" category in menu panel 
Click on "Named Views (EN)"

### What is expected ?

Clicking on "Named Views (EN)" should redirect to the corresponding ID, and set the text's color to green (active).

### What is actually happening?

The title "Named Views (EN)" in the left menu panel on is not green green.
Clicking on it does nothing (should redirect).

### Additional comments?

Clicking on "Transitions" sets "Named Views (EN)" to active in the menu
Clicking on "Middleware" sets "Transition" to active in the menu

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c237">#c237</a>)</em></sub></div>

**Comment by GuiguiWeb** [comment]
@manniL Fix with #1791
