### ISSUE TITLE
Doc for Google Tag Manager

### ISSUE THREAD

**Issue by Burzmalian** [nuxt/docs#179]
I would recommend adding documentation about adding Google Tag Manager and using Google Analytics through that.   GTM has history change tags allowing for easy GA tracking with SPAs.

Gyles

**Comment by pi0** [comment]
Hi @briangonzalez . Nuxt community even already has a [google-tags-manager](https://github.com/nuxt-community/modules/tree/master/modules/google-tag-manager) module. That would be awesome if you are interested sharing your experiences on it's docs. PRs are welcome :)

**Comment by briangonzalez** [comment]
eh?

**Comment by pi0** [comment]
What?

**Comment by husayt** [comment]
Closing since there is necessary information [here](https://github.com/nuxt-community/modules/tree/master/packages/google-tag-manager)
