### ISSUE TITLE
Document $nuxt.refresh()

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#1813]
Document https://github.com/nuxt/nuxt.js/pull/6194

**Comment by johnson-jnr** [comment]
Hi @manniL I'll love to contribute to this. How can I go about it
Thanks!

**Comment by debs-obrien** [comment]
hi this has now been documented in the new docs

**Comment by mornir** [comment]
@debs-obrien Hi! where can I find it in the docs? I was expecting to see it here: https://nuxtjs.org/guides/internals-glossary/$nuxt

**Comment by manniL** [comment]
> 
> 
> @debs-obrien Hi! thanks for documenting it. Where can I find it in the docs? I was expecting to see it here: [nuxtjs.org/guides/internals-glossary/$nuxt](https://nuxtjs.org/guides/internals-glossary/$nuxt)

https://nuxtjs.org/guides/concepts/context-helpers#refreshing-page-data

**Comment by debs-obrien** [comment]
good point. it probably should be added to the glossary too. Thanks for pointing it out @mornir will add it to my tasks
