### ISSUE TITLE
Nuxtjs doc open to translate to another language?

### ISSUE THREAD

**Issue by VadiForte** [nuxt/docs#184]
Hi, Im from Thailand. And I found Nuxtjs is very useful and I think it would be great if nuxtjs let ppl to translate to they language 🙂

**Comment by alexchopin** [comment]
Hi @VadiForte, Of course, it's open to other languages :) 
You can fork this repo and duplicate the `en` folder (which is the base of translated file), rename it with the ISO code, translate all files and do a Pull Request.
However, I recommend you to use the v1 branch.

**Comment by VadiForte** [comment]
Thank you, I'll try 👍

**Comment by VadiForte** [comment]
Ehh, Im not sure what's going on here, but I try use v1 branch as you said, and I found it have a bug where someone already ask in the issue. So, I try the master with "npm run dev" and now it work.

```
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: api.js
[nodemon] starting `node api.js gh-hook.js`
Building files...
Building menu...
Building languages...
Fetching releases...
Watch files changes...
Server listening on localhost:4000
```

but when I go to `localhost:4000`, it just said `File not found`

How to solve this? 🤔

**Comment by pi0** [comment]
@VadiForte You have to also clone and route [nuxtjs.org](https://github.com/nuxt/nuxtjs.org) repo which is front end part listening to port `3000` Both should be running locally for preview :)

**Comment by mika76** [comment]
Just ran into this too - maybe it should be placed in the build instructions?

**Comment by pi0** [comment]
PR Welcome 👍

**Comment by Atinux** [comment]
Hi :)

You can use GitLocalize to easily update the Thai docs: https://gitlocalize.com/repo/100/th
