### ISSUE TITLE
Codesandbox Forbidden Access

### ISSUE THREAD

**Issue by andrewmurraydavid** [nuxt/docs#1843]
### Version

[v2.3.4](https://github.com/docs/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/i18n?from-embed](https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/i18n?from-embed)

### Steps to reproduce

1. Access https://nuxtjs.org/examples/i18n/
2. Try to access the codesandbox example

### What is expected ?

I expect to be able to play around with the example and see the source code.

### What is actually happening?

Codesandbox return a 403 Forbidden.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c247">#c247</a>)</em></sub></div>

**Comment by andrewmurraydavid** [comment]
This issue is now fixed. Thank you!

**Comment by Deckluhm** [comment]
There is still a 403 error on the reproduction link + most (all?) CodeSandbox links display the following message:

> **Not Found**
>
> We could not find the sandbox you're looking for.

Examples:
- https://nuxtjs.org/examples/auth-routes
- https://nuxtjs.org/examples/auth-external-jwt

[CodeSandbox status page](https://status.codesandbox.io/) says everything is fine on their side.
