### ISSUE TITLE
Broken Hookable reference, not replaced by Hable after releasing Nuxt v2.9.2 

### ISSUE THREAD

**Issue by Igloczek** [nuxt/docs#1872]
### Version

[2.9.2](https://github.com/docs/releases/tag/2.9.2)

### Reproduction link

[https://nuxtjs.org/guide/modules#run-tasks-on-specific-hooks](https://nuxtjs.org/guide/modules#run-tasks-on-specific-hooks)

### Steps to reproduce

The link to Hookable is broken, because this file was removed in v2.9.2 while replacing the solution with Hable

### What is expected ?

Working link, with a list of available hooks.

### What is actually happening?

404

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c250">#c250</a>)</em></sub></div>

**Comment by Atinux** [comment]
Thank you @Igloczek :)
