### ISSUE TITLE
404 on https://ru.nuxtjs.org/faq

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#20]
<img width="1440" alt="screen shot 2017-01-21 at 13 32 22" src="https://cloud.githubusercontent.com/assets/1452165/22173795/37f6d78a-dfde-11e6-8106-8c3d6767cf25.png">

**Comment by alexchopin** [comment]
fixed 👍

**Comment by gbezyuk** [comment]
Thanx!
