### ISSUE TITLE
Update Installation Docs to Reflect New Installation Process

### ISSUE THREAD

**Issue by stuft2** [nuxt/docs#2019]
### What problem does this feature solve?

The Installation documentation page leaves out some crucial elements that developers are bound to have questions about. For example: when choosing TypeScript as your programming language, a follow up questions asks you to choose the runtime for TypeScript. The only way a developer could know more about this option is to find the feature request on GitHub and follow the conversation.

I propose that the Installation documentation page be updated to reflect exactly what the installation process is and continues to provide links or short descriptions of each option. If implemented, this will help developers (especially rookies) understand the components they want or can install, provide them a direction to learn about topics they are unfamiliar with, and complete the documentation so nothing is missing.

### What does the proposed changes look like?

The [Installation documentation page](https://nuxtjs.org/guide/installation) will better reflect all the steps and options available in the `create-nuxt-app` installation process.

**Comment by debs-obrien** [comment]
Thanks for the feedback. we have revamped the docs and will be releasing them very shortly and the aim is to help new users get started easily with nuxt. when we do release them (within the next few weeks) then I would love to hear your feedback on them. Thanks and hope you are having fun with Nuxt.js 💚
