### ISSUE TITLE
srcDir and rootDir alias

### ISSUE THREAD

**Issue by bskimball** [nuxt/docs#208]
after upgrading to rc7 I noticed a difference in the alias. The example in the docs no longer works
```javascript
~assets/your_image.png
```
I had to change it to 
```javascript
~/assets/your_image.png
```

I am using the defaults. I can create a pr for the change in the docs but I was curious if anyone else had this issue or if I somehow did not update properly.

**Comment by Atinux** [comment]
Hi @bskimball 

It's because only english docs are up to date right now
