### ISSUE TITLE
As @snake575 already mentioned. When using `nuxt/postcss8` you still get the following warning.

### ISSUE THREAD

**Issue by ghost** [nuxt/docs#2133]
As @snake575 already mentioned. When using `nuxt/postcss8` you still get the following warning.

```bash
 WARN  postcss@8.2.8 is installed but ^7.0.32 is expected 
```

I tried to fix it, only to find out that this is **expected behavior** now.

_Originally posted by @MartinMa in https://github.com/nuxt/nuxt.js/issues/8087#issuecomment-800167111_

**Comment by pi0** [comment]
Hi @OsvaldoRino. Can you please confirm what nuxt version are you using? (from CLI banner). It is fixed in 2.15.4+
