### ISSUE TITLE
Using a localization platform

### ISSUE THREAD

**Issue by gokaygurcan** [nuxt/docs#214]
Hi,
I'm just wondering why you're not using a localization platform such as [transifex](https://www.transifex.com/) or [CrowdIn](https://crowdin.com/)? They both have open source tier and this project is a perfect candidate imho. 

Thanks for your answers in advance. 

Cheers,
G.

**Comment by Atinux** [comment]
Hi @gokaygurcan 

Actually we are using https://gitlocalize.com/repo/100 :)

**Comment by gokaygurcan** [comment]
Hi,
I was either looking with my nose or this information is not visible. But thanks anyways!
