### ISSUE TITLE
Change description in EN/Guide/Routing

### ISSUE THREAD

**Issue by rspt** [nuxt/docs#239]
Hello,

The description, `Nuxt.js use the file-system to generate the routes of your web applications, it's as simple as PHP to create routes.`,  in [Guide/Routing](https://github.com/nuxt/docs/blob/master/en/guide/routing.md) bothers me for two reasons:
- It's irrelevant if we haven't used PHP
- The wording "as simple as" can be frustrating for the newcomers who don't find it "simple".

Should we change it to something like: `Nuxt.js use the file-system to generate the routes of your web applications.`

Thanks

(View the original discussion, in french, here: https://github.com/vuejs-fr/nuxt/pull/11/files/52bf57bc0b8769b29762f07577ad9f8fefd9bae2#r139283562)

**Comment by Atinux** [comment]
I agree, could you do a PR on it @rspt ?

**Comment by rspt** [comment]
Et voilà! :)

**Comment by Atinux** [comment]
Merci :)
