### ISSUE TITLE
redirects and docs for 'em

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#24]
Hi there!
Is there a possibility to specify redirects in Nuxt?
And if there is, is there any documentation for it?

(initially mistakenly opened at https://github.com/nuxt/nuxtjs.org/issues/11)

**Comment by alexchopin** [comment]
Hi, yes you can do redirections with the key `redirect` in the context object pass through data() and fetch().
The [documentation](https://nuxtjs.org/api/) is not a specific page for this key unfortunately.

**Comment by gbezyuk** [comment]
@alexchopin thanx! Is this the only way possible? Shouldn't there be a more declarative approach?
