### ISSUE TITLE
Schema picture is showing a misspelled `Navigate` transition.

### ISSUE THREAD

**Issue by m99coder** [nuxt/docs#248]
The [Schema](https://github.com/nuxt/docs/raw/master/nuxt-schema.png) image is showing a misspelled `Navigate` transition on the right.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c43">#c43</a>)</em></sub></div>

**Comment by Atinux** [comment]
See https://github.com/nuxt/nuxtjs.org/pull/103
