### ISSUE TITLE
global fetch and docs for it

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#25]
Hi there!

Sometimes there's a need to have data fetched not for a particular page, but for the whole app. Is there a way to specify a global `fetch` method? If there's one, are there any docs on this issue?

I've tried specifying `fetch` for the layout, and it didn't work. Neither it would work for the component, I guess.

I belive we should update the code at [/lib/app/server.js#L94](https://github.com/nuxt/nuxt.js/blob/master/lib/app/server.js#L94), adding layout's fetch method there.

As an illustration on why it's an important feature, consider contact information editable via admin and coming from backend via API; or a a simple list of pages working the same way.

**Comment by alexchopin** [comment]
Hi, 
I think the `nuxtServerInit()` function is the global fetch you are talking about.
[Documentation](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action)
I forgot to tell you on the last issue, if you wish to create new docs for some part you think is missing on the documentation you are welcome :)
