### ISSUE TITLE
FAQ Sidemenu not showing

### ISSUE THREAD

**Issue by chabib** [nuxt/docs#270]
FAQ Sidemenu not showing
[https://nuxtjs.org/faq](https://nuxtjs.org/faq)

**Comment by Atinux** [comment]
Fixed, thank you @chabib

**Comment by chabib** [comment]
Out of curiosity, what was the problem?

**Comment by Atinux** [comment]
I forgot a semicolon :)

https://github.com/nuxt/docs/commit/28051824f9be7d5b9f76cc7411a06c5a13805f7f

**Comment by chabib** [comment]
You meant a comma, right?
Anyway, what if we can worry less about the comma? 
You know, coffeescript.
What do you think about it, since version 2 has been released with es6 features?

**Comment by Atinux** [comment]
Yes a comma, I always forgot this name in english.

Actually it's json files, that's why it's so strict. It's only because I did not test it before merging :)
