### ISSUE TITLE
Vuex.Store docs doesn't mention setting config option for $store

### ISSUE THREAD

**Issue by lmj0011** [nuxt/docs#29]
this: 
> Vuex.Store instance. Available only if store: true is set in nuxt.config.js

https://nuxtjs.org/api/#context

should be somewhere at the top of this:
https://nuxtjs.org/guide/vuex-store

otherwise, you're going to have to import it in your .vue

**Comment by Atinux** [comment]
Nice catch @lmj0011 

The `store` option in the `nuxt.config.js` file has been removed, now nuxt.js knows when you want to use the store directly if a `store` folder exits.
