### ISSUE TITLE
[fr] Should we update the translation credits?

### ISSUE THREAD

**Issue by rspt** [nuxt/docs#294]
Dans le readme, je suis toujours crédité comme traducteur et mainteneur principal. Je pense que ce serait bien de changer ça pour mettre en avant Vue.js FR.

Qu'en pensez-vous @Haeresis et @forresst?

**Comment by Haeresis** [comment]
Bonne idée. Je vais faire une PR. (Je pense que cette issue devrait être sur vuejs-fr/nuxt X)

**Comment by forresst** [comment]
Si c'est toi qui le propose, je ne peux qu'approuver.

**Comment by Haeresis** [comment]
Je te laisse en « Primary translator » étant donné q'un bon 90% du texte ici est issu de tes traductions :)

**Comment by rspt** [comment]
> Bonne idée. Je vais faire une PR. (Je pense que cette issue devrait être sur vuejs-fr/nuxt X)

@Haeresis J'ai checké en vitesse mais j'ai pas trouvé le readme originel sur vuejs-fr/nuxt, du coup je l'ai mise ici ^^

> Si c'est toi qui le propose, je ne peux qu'approuver.

Bah ça me semble normal, si c'est la communauté qui s'en occupe, de changer ça :)

> Je te laisse en « Primary translator » étant donné q'un bon 90% du texte ici est issu de tes traductions :)

Ca me va :)
