### ISSUE TITLE
/api/context is not found in japanese edition.

### ISSUE THREAD

**Issue by dotneet** [nuxt/docs#336]
https://ja.nuxtjs.org/api/context
this page is linked from https://ja.nuxtjs.org/api#asyncdata-%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c49">#c49</a>)</em></sub></div>

**Comment by potato4d** [comment]
resolved?
