### ISSUE TITLE
can you include vue-beauty for me? as it can  not import simply by import.

### ISSUE THREAD

**Issue by owey0312** [nuxt/docs#337]
when [import Beauty from 'vue-beauty'], the console print window or document not define.
as i saw that your website FAQ has solved this problem, but when i do so, the label <v-button> can not be translate by vue also in browser. 
i am in trouble of it, wait for your help.

vue-beauty git address : https://github.com/FE-Driver/vue-beauty

**Comment by husayt** [comment]
this is documentation repo. Please raise your issue at nuxt's repo if you still have this issue
