### ISSUE TITLE
Auth Routes Online Examples

### ISSUE THREAD

**Issue by appurist** [nuxt/docs#342]
The Auth Routes example ([here](https://nuxtjs.org/examples/auth-routes)) has both [Live Demo](https://nuxt-auth-routes.glitch.me/) and [Live Edit](https://nuxt-auth-routes.glitch.me/) buttons, and launch the example code hosted on glitch.me. 

When run, the login form is shown, however _logging in appears to have no effect_. There is no access to auth routes in the demo.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c51">#c51</a>)</em></sub></div>

**Comment by appurist** [comment]
I should note that the Auth Routes example, when downloaded, seems to work just fine.

**Comment by fractalf** [comment]
+1
The examples are kind of a mess. None of the live demos actually work (I tried the top 5 links [here](https://nuxtjs.org/examples).

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
