### ISSUE TITLE
Facebook Comments integration

### ISSUE THREAD

**Issue by menteora** [nuxt/docs#343]
Hi, can you help me to apply your suggestion to facebook comments?

- your docs: https://github.com/nuxt/docs/blob/master/en/faq/google-analytics.md
- facebook docs: https://developers.facebook.com/docs/plugins/comments/

I tried but without results
Thanks

**Comment by husayt** [comment]
Closing as this is not directly related to nuxt documentation

**Comment by menteora** [comment]
Hi, if you want integrate inside documentation, we use `"vue-no-ssr": "^0.2.2"` component for only client side rendering.

``` html
<template>
  <no-ssr>
    <div
      :permalink="permalink"
    >
      <div id=fb_thread class="text-xs-center">
        <div class="fb-comments" :data-href="baseUrl" data-numposts="5" data-width="100%"></div>
      </div>
      <div id="fb-root"></div>
      <script>
        (function (d, s, id) {
          var js
          var fjs = d.getElementsByTagName(s)[0]
          if (d.getElementById(id)) return
          js = d.createElement(s); js.id = id
          js.src = '//connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v2.8&appId={{$store.state.facebookAppId}}'
          fjs.parentNode.insertBefore(js, fjs)
        }(document, 'script', 'facebook-jssdk'))
      </script>
    </div>
  </no-ssr>
</template>
```

were **baseUrl** is article link and **$store.state.facebookAppId** is facebook Id

**Comment by wowthemes** [comment]
I think it works [hanjeahwan](https://github.com/nuxt/nuxt.js/issues/1945#issuecomment-343734883)

**Comment by quyetDK** [comment]
i 've problem. while render page first time my " facebook comment" can not render in DOM. Only when reload page then ok. my code =>
`<div id="article-comment" :data-href="getUrl()" data-width="100%" data-numposts="10" />
mounted() { this.$initFbSdk() }
Vue.prototype.$initFbSdk = () => {
  window.fbAsyncInit = () => {
    FB.init({
      appId: 'myid',
      autoLogAppEvents: true,
      xfbml: true,
      version: 'v3.1'
    })
  }
}

export default ({ app }) => {
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.1&appId=myid&autoLogAppEvents=1';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
}
`

**Comment by Victor116** [comment]
quyetDK you need create component copy and paste this code

`<template lang="pug">
  no-ssr
    #fb-root.column.is-12-desktop.is-12-mobile
      .fb-comments#fb-comments(:data-href="baseUrl" data-width="100%" data-numposts="5")
</template>
<script>
let stopSetTime = null;
export default {
  props: {
    baseUrl: {
      type: String,
			required: true,
			default: ''
    }
  },
  mounted() {
    stopSetTime = setTimeout(() => {
      this.initCreationFacebookComments()
    }, 3000);
  },
  methods: {
    initCreationFacebookComments(){
      clearTimeout(stopSetTime); // Paramos el Tiempo

      FB.XFBML.parse() //<- This is import to refresh comments see the link add

      window.fbAsyncInit = function() {
        FB.init({
          appId: 'you'r id app in string',
          cookie: true,
          xfbml: true,
          version: 'v4.0'
        });
      };

      (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    }
  }
}
</script>`

https://stackoverflow.com/questions/16384098/facebook-comment-not-working

**Comment by Victor116** [comment]
Sorry these code is bad, the correctly is:

<script>
export default {
  props: {
    baseUrl: {
      type: String,
			required: true,
			default: ''
    }
  },
  mounted() {
    window.fbAsyncInit = function() {
      FB.init({
        appId: '2261192517313442',
        cookie: true,
        xfbml: true,
        version: 'v4.0'
      });
    };

    console.log(window.fbAsyncInit);

    (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_ES/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    setTimeout(() => {
      this.initCreationFacebookComments()
    }, 5000);
  },
  methods: {
    initCreationFacebookComments(){
      FB.XFBML.parse()
    }
  }
}
</script>

**Comment by Victor116** [comment]
> <template lang="pug">
  no-ssr
    #fb-root.column.is-12-desktop.is-12-mobile.pl-0
      .fb-comments.column.is-12-desktop.is-12-mobile(:data-href="baseUrl" data-width="100%" data-numposts="5")
</template>
<script>
export default {
  props: {
    baseUrl: {
      type: String,
			required: true,
			default: ''
    }
  },
  mounted() {
    window.fbAsyncInit = function() {
      FB.init({
        appId: 'you're id in string',
        cookie: true,
        xfbml: true,
        version: 'v4.0'
      });
    };

    (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_ES/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    setTimeout(() => {
      this.initCreationFacebookComments()
    }, 3000);
  },
  methods: {
    initCreationFacebookComments(){
      FB.XFBML.parse() // Refres comments the XFBML 
    }
  }
}
</script>

**Comment by quyetDK** [comment]
> You're need is refres the XFBML, i create a component this my code
> 
> > ` 
> > no-ssr
> > #fb-root.column.is-12-desktop.is-12-mobile.pl-0
> > .fb-comments.column.is-12-desktop.is-12-mobile(:data-href="baseUrl" data-width="100%" data-numposts="5")
> > 
> > 
> > <script>
> > export default {
> >   props: {
> >     baseUrl: {
> >       type: String,
> > 			required: true,
> > 			default: ''
> >     }
> >   },
> >   mounted() {
> >     window.fbAsyncInit = function() {
> >       FB.init({
> >         appId: 'you're id in string',
> >         cookie: true,
> >         xfbml: true,
> >         version: 'v4.0'
> >       });
> >     };
> > ```
> > (function(d, s, id){
> >   var js, fjs = d.getElementsByTagName(s)[0];
> >   if (d.getElementById(id)) {return;}
> >   js = d.createElement(s); js.id = id;
> >   js.src = "//connect.facebook.net/es_ES/sdk.js";
> >   fjs.parentNode.insertBefore(js, fjs);
> > }(document, 'script', 'facebook-jssdk'));
> > 
> > setTimeout(() => {
> >   this.initCreationFacebookComments()
> > }, 3000);
> > ```
> > 
> > 
> > },
> > methods: {
> > initCreationFacebookComments(){
> > FB.XFBML.parse() // Refres comments the XFBML
> > }
> > }
> > }
> > </script>`
> > https://stackoverflow.com/questions/16384098/facebook-comment-not-working

thanks @Victor116 . i did it. Thank you very much !

**Comment by thaycacac** [comment]
```js
FB.XFBML.parse()
```
worked for me
