### ISSUE TITLE
how to require some libraries only for the server

### ISSUE THREAD

**Issue by TroubleZjb** [nuxt/docs#358]
> In case you need to require some libraries only for the server, you can use the process.server variable set to true when webpack is creating the server.bundle.js file.

I don't know what exactly I should do.

*For example I want to take data from Mongodb with mongoose into `asyncData`. How can i make mongoose server-only?*

`~/mongo/mongo-test.js`
```js
import mongoose from 'mongoose'

const user = new mongoose.Schema({
    // some definition
})

const userModel = mongoose.model('user',user)

export function findSomeone(){
    userModel.find({
        // find datas
    } ,callback)
}
```

`~/router/index.vue`
```vue
<template>
    <div></div>
</template>

<script>
import mongoTest from '~/mongo/mongo-test.js'

export default {
  asyncData: (context) => { if (context.isServer) { mongoTest.findSomeone() } },
}
</script>

<style>
</style>
```

**Comment by Atinux** [comment]
Hi @TroubleZjb 

You can use `process.server` into your page:

`~/router/index.vue`:
```vue
<template>
    <div></div>
</template>

<script>
export default {
  asyncData: (context) => {
    const mongoTest = (process.server ?  require('~/mongo/mongo-test.js') : null)
    if (process.server) {
      mongoTest.findSomeone()
    }
  },
}
</script>

<style>
</style>
```

But **I really don't recommend this approach** but instead create an API using MongoDB and then calling this API with axios from both client-side and server-side.
