### ISSUE TITLE
Need more crisp and up-to-date value proposition and CTA for Nuxt.js in docs

### ISSUE THREAD

**Issue by SLathropDP** [nuxt/docs#359]
I get that Nuxt.js began life as "Next.js for Vue.js". But Nuxt.js has its own identity and value proposition in the Vue.js ecosystem and it would benefit from a more crisp and up-to-date value proposition and call-to-action.

Right now, unless someone has used Next.js or has watched some of the YouTube videos about Nuxt.js it's perhaps difficult to really get the message about the value that Nuxt.js provides from reading the docs.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c57">#c57</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @SLathropDP 

Thank you very much, we are currently working on the new documentation website that will inform in details what is Nuxt.js and all its core features.

We will also provide more informations of who is maintaining it, how stable it is and the best practices to deploy for production :)

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
