### ISSUE TITLE
Translate to pt-BR (Portuguese Brazil)

### ISSUE THREAD

**Issue by vitornogueira** [nuxt/docs#373]
I want to start translating to pt-BR (Portuguese Brazil), how do I add my fork in GitLocalize?

Fork Link: https://github.com/devtranslate/docs

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c58">#c58</a>)</em></sub></div>

**Comment by ErickPetru** [comment]
@vitornogueira there are guys actually planning this translation at [vuejs-br](https://github.com/vuejs-br) comunity. Do you want to join us?

**Comment by ErickPetru** [comment]
@Atinux can you add **Portuguese (Brazil)** to the GitLocalize translate list or should we go by ourselves forking the this repo like we do in the main Vue.js docs?

**Comment by vitornogueira** [comment]
Nice! We fork the repository to devtranslate organization (https://github.com/devtranslate/docs). Can we work on that fork or will it have a fork for the @vuejs-br?

**Comment by derevandal** [comment]
@vitornogueira Vue Brazilian Community is centralized on VueJs-Br organization. Do you mind keeping the repository there?

**Comment by Atinux** [comment]
Hi there, it's awesome to have Brazilian translation coming!

I believe it's better to fork the repository so you can stay in sync with `master` branch, I think @Haeresis can explain more about his process which is really good

**Comment by vitornogueira** [comment]
Hi @derevandal. If you want we can work on the fork of the @vuejs-br organization, no problems 😉

**Comment by ErickPetru** [comment]
@vitornogueira, the fork https://github.com/vuejs-br/nuxt-docs is waiting for you.

@Atinux, we already work this way with the vuejs.org repo. But how you'd like to receive our updates to deploy, maybe pull requets of the **pt-br** folder to the main repo?

**Comment by Atinux** [comment]
Pull requests to thr `pt-br` folder will be perfect :)

**Comment by vitornogueira** [comment]
Thanks @ErickPetru

**Comment by derevandal** [comment]
Thanks all.
@ErickPetru could u add your fork in GitLocalize? 
Or u should wait @Haeresis and @Atinux?

**Comment by Haeresis** [comment]
We do not use GitLocalize accross our Vuejs-FR process but we have a process to translate and review all togheter and better, a process to see all changes from last translation update to set up-to-date the documentation with English version. If you do not want use GitLocalize or if you not already have a process I can explain our process (or find post where I explain it) :) Let me know if it's useful now or let me know that later ;)

Good Luck ;)

**Comment by derevandal** [comment]
@Haeresis thanks bro! now, we fork this repo, clone en folder and start translate making pl on your fork. what process do u use?

**Comment by Haeresis** [comment]
## Principe alone

Manage your translation into two branch on your translation project your fork from `nuxt/docs`.

1. The `master` branch will be reserved to propose PR from `<your-repo>/docs:master` to `nuxt/docs:master`.
2. The `working` branch into which you will translate into `en` directory directly from EN to PT.

Your `working` branch will be upstreamed from `nuxt/docs:master`. That means each time an update will be done into the original `en` directory from `nuxt/docs:master`, a conflict will appear in your `<your-repo>/docs:working` at the same already translated file and line. That allows you to track all update in future, and update it.

When the `<your-repo>/docs:working` EN directory is enough translated / updated, you copie/past the `en` content into the `pt` directory of `<your-repo>/docs:master`. From now just do a PR `<your-repo>/docs:master` to `nuxt/docs:master` to update `pt` in orginal fork.

## Work with a team

To allows more one person to translate files. Each translator should create it's own fork from `<your-repo>/docs:working`, translate the wanted file, and do a PR to `<your-repo>/docs:working`. That will allows all teams to review the PR and see line by line what EN line is become an PR line (and correct error translation/typo).

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
