### ISSUE TITLE
Initialize The Translation to German

### ISSUE THREAD

**Issue by zoosky** [nuxt/docs#397]
Hi

I'd like to start the translation to German.

What is needed to do to get the starting tree `de`?

Thanks!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c61">#c61</a>)</em></sub></div>

**Comment by Zefool** [comment]
I'd guess the folder structure is the same for all languages, so maybe just initialize a directory, copy the lang.json and change the appropriate values?

**Comment by Freakspot** [comment]
Just stumbled upon this issue. If you're still interested all you'll have to do now is sync your fork and translate the files in the newly created `de` directory one by one @zoosky.

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
