### ISSUE TITLE
Routing dynamic generation page configuration problem: how to generate more than 10,000 data?

### ISSUE THREAD

**Issue by imbin** [nuxt/docs#428]
https://github.com/nuxt/docs/blob/master/zh/api/configuration-generate.md

module.exports = {
  generate: {
    routes: [
      '/users/1',
      '/users/2',
      '/users/3'
    ]
  }
}

nuxt:generate Generate file: /index.html +21ms
nuxt:generate Generate file: /users/1/index.html +31ms
nuxt:generate Generate file: /users/2/index.html +15ms
nuxt:generate Generate file: /users/3/index.html +23ms

how to generate more than 10,000 data?

**Comment by husayt** [comment]
Closing as this is not documentation issue
