### ISSUE TITLE
Non-ASCII anchor navigation issue

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#5]
Hi guys! Please take a look at https://github.com/translation-gang/ru.docs.nuxtjs/issues/10
I know that in original Vue's docs the similar problem is solved (in fact, you don't even need to specify any anchor manually, as we do now in `menu.json`'s `to` params).

**Comment by Atinux** [comment]
Hi @gbezyuk 

Thank you, we will take a look and come back to you quickly.

**Comment by Atinux** [comment]
@gbezyuk it's fixed in this commit: https://github.com/nuxt/docs/commit/26aac06b8672afefbca0e93c08f1a792ab35ece6

Please update from the master branch.

**Comment by gbezyuk** [comment]
@Atinux thank you!
