### ISSUE TITLE
id key in the head method

### ISSUE THREAD

**Issue by ckhrysze** [nuxt/docs#517]
The documentation at https://nuxtjs.org/api/pages-head advises to use 'hid' to avoid child meta name clashes, but then links to the vue-meta docs which instead references a 'vmid' key. I'm not sure if this is intentional, or one of the two being out of date.
I can dig in at some point and attempt to figure it out. If someone just knows though, I will happily submit a pull request to which ever documentation is out of sync.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c65">#c65</a>)</em></sub></div>

**Comment by harryhazza77** [comment]
Hi @ckhrysze I was about to submit a PR but did a bit more digging and found this - https://github.com/nuxt/nuxt.js/blob/83c1e085a5bd8cdffb4c70dbef61c2604a3842bb/lib/app/index.js#L35 so hid is valid but admit its not clear when viewing the referenced documentation link

**Comment by manniL** [comment]
Resolved with #887
