### ISSUE TITLE
The Chinese document, the page in the view section and the layout switch has a bug.

### ISSUE THREAD

**Issue by Y-Ulia** [nuxt/docs#529]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c67">#c67</a>)</em></sub></div>

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
