### ISSUE TITLE
document translate still 0.9.9 but it show 0.10.0

### ISSUE THREAD

**Issue by ausir0726** [nuxt/docs#58]
for 0.10.0 breaking change .

like asyncData , or generate.route

in document cn , jp , ru is the old version . ( 0.9.9 )
I know document need time make it correct

but if show 0.10.0 will let some people misunderstanding .
especially breaking change .

so , I think if translate not prepare for 0.10.0 is should only display 0.9.9
( maybe someday update to 1.0.0 .... if no translate version , it should show , no translate for this version , please see English version )

or , It should be fix correct content version ASAP.

I know some people very depend there native language document , but wrong version display will misleading them . ( I will told you someone is my friend 😆  )

✋ Thanks a lot to all the contributors and people helping to make Nuxt.js better! ✋

**Comment by ausir0726** [comment]
the version 0.10 , but contnet is 0.9.9 ( Breaking change )

If that can show 0.9.9 will more clear, ( or like angular have a dropdown list choose version )
![capture](https://cloud.githubusercontent.com/assets/7247064/24311120/b6123bae-110d-11e7-8af1-9aa1577db41d.PNG)

**Comment by Atinux** [comment]
Good catch @ausir0726 

I will put the version to `0.9.9` until the different languages are up to date.

**Comment by Atinux** [comment]
The website is now updated, thank you @ausir0726 😄
