### ISSUE TITLE
Flag issue

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#6]
Hi guys, please take a look at https://github.com/translation-gang/ru.docs.nuxtjs/issues/11
I wonder, where should I put a Russian flag image in order to make it work?

**Comment by Atinux** [comment]
@gbezyuk it's in the static/flags/ folder

@alexchopin can you add the flag for Russia?

**Comment by alexchopin** [comment]
Hi, this [commit](https://github.com/nuxt/nuxtjs.org/commit/4cd71953dd00343699babc54ca70d35289b848a1) should fix this issue.

**Comment by gbezyuk** [comment]
@alexchopin thanx, it totally works ;)
