### ISSUE TITLE
Following example for VueX store modules-mode throws "Cannot read property 'state' of undefined"

### ISSUE THREAD

**Issue by primoz-k** [nuxt/docs#604]
### Version

[1.4.0](https://github.com/nuxt/docs/releases/tag/1.4.0)

### Reproduction link

[https://nuxtjs.org/guide/vuex-store#modules-mode](https://nuxtjs.org/guide/vuex-store#modules-mode)

### Steps to reproduce

I'm following an example for initiating store with modules-mode, but keep getting "Cannot read property 'state' of undefined" exception.

### What is expected ?

TODO example should not break.

### What is actually happening?

"Cannot read property 'state' of undefined" is thrown.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/docs/issues/c93">#c93</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @primoz-k 

I tried on my end but could not reproduce the issue, could you remix https://glitch.com/edit/#!/nuxt-hello-world and show me the error?
