### ISSUE TITLE
Search at nuxtjs.org doesn't seem to work.

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#7]
subj

**Comment by Atinux** [comment]
@gbezyuk we are about it, we wait for the documentation to be finished before implementing https://community.algolia.com/docsearch/

**Comment by gbezyuk** [comment]
okay, than we'll also need different algolia configs for translations and an obvious way for receiving a new key for new translations (vuejs.org's approach isn't the best example in this area =()

**Comment by Atinux** [comment]
The search is now active!

The configuration: https://github.com/algolia/docsearch-configs/blob/master/configs/nuxtjs.json

**Comment by gbezyuk** [comment]
@Atinux sooo, did you update https://ru.nuxtjs.org ? Still doesn't seem to work there.

**Comment by limichange** [comment]
Search at `https://cn.nuxtjs.org` doesn't work too.
