### ISSUE TITLE
End to end testing doesn't work with spa mode.

### ISSUE THREAD

**Issue by aintek4** [nuxt/docs#721]
"End to End Testing" tutorial does't work When using spa mode because spa mode does't make page content.

The end to end testing using spa mode is hang up and never call `test.after`.

My proposal for test file `test/index.test.js`:
```
test.before('Init Nuxt.js', async t => {
  const rootDir = resolve(__dirname, '..')
  let config = {}
  try { config = require(resolve(rootDir, 'nuxt.config.js')) } catch (e) {}
  config.mode = 'universal' // my proposal
  config.rootDir = rootDir // project folder
  config.dev = false // production build
  nuxt = new Nuxt(config)
  await new Builder(nuxt).build()
  nuxt.listen(4000, 'localhost')
})
```
Please consider that.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c106">#c106</a>)</em></sub></div>

**Comment by aintek4** [comment]
@Atinux

This issue is not question, but bug-report.
The End to end testing is hang up when using spa mode.

I recommend add ` config.mode = universal` in `test.before`.

If you agree my proposal, I will send PR.

**Comment by Atinux** [comment]
Update to bug-report.

Sure it's always good to make it clearer for the end-to-end testing :)

**Comment by aintek4** [comment]
@Atinux 

I sent PR: https://github.com/nuxt/docs/pull/723 .
Please accept that.

**Comment by Atinux** [comment]
Merged, thank you @aintek4
