### ISSUE TITLE
Can I and potato4d merge PR for Japanese translations?

### ISSUE THREAD

**Issue by inouetakuya** [nuxt/docs#744]
@Atinux 

Hi, I and HANATANI Takuma(@potato4d) are primary maintainers for Japanese translation.

Could you grant us authorities to merge pull requests for Japanese translation?

### Why?

We Japanese translation team will start project to complete Japanese translations soon.

We will review and update PR in this nuxt/docs many times and we know well when PR is ready to merge.

**Comment by inouetakuya** [comment]
@Atinux 

Could you re-open this issue because this is not question ?  🙏

**Comment by Atinux** [comment]
Hi @inouetakuya 

I gave you access to merge PR on the repository as well as @potato4d :)

**Comment by inouetakuya** [comment]
Thank you !! 😀

**Comment by inouetakuya** [comment]
@Atinux 

Sorry, but It seems to be needed `write access` 🙏 

![image](https://user-images.githubusercontent.com/634357/45166339-c1d67880-b231-11e8-9c1d-75fa8dc51926.png)

**Comment by inouetakuya** [comment]
Very sorry, I misunderstood 🙏 

I have access to merge 😀 

![image](https://user-images.githubusercontent.com/634357/45166680-8c7e5a80-b232-11e8-8ec1-beb6280dbf9e.png)
