### ISSUE TITLE
google analytics tracks Title of previous page

### ISSUE THREAD

**Issue by toyflish** [nuxt/docs#75]
Hi I followed the [google analytics plugin](https://github.com/nuxt/docs/blob/master/en/faq/google-analytics.md). It works for the first request (serverside-rendered), but on the following (browser-rendered) it tracks pages but with the title of the previous page-request.
[I'm inserting html-title via vue-meta](https://github.com/toyflish/tbone-front/blob/master/pages/_slug/index.vue#L44), I guess the afterEach-callback fires to early?

**Comment by Atinux** [comment]
You can add a `setTimeout` to wait for meta to be updated.
