### ISSUE TITLE
API docs mention deprecated build.vendor

### ISSUE THREAD

**Issue by renspoesse** [nuxt/docs#781]
### Version

[master](https://github.com/docs/releases/tag/master)

### Reproduction link

[https://nuxtjs.org/api/configuration-build#vendor](https://nuxtjs.org/api/configuration-build#vendor)

### Steps to reproduce

https://nuxtjs.org/api/configuration-build#vendor mentions how build.vendor can be used, while https://nuxtjs.org/guide/release-notes states that it's deprecated.

### What is expected ?

The section should be removed

### What is actually happening?

The section is still there

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c110">#c110</a>)</em></sub></div>

**Comment by galvez** [comment]
Thank you @renspoesse -- will remove it.

**Comment by manniL** [comment]
Same for https://nuxtjs.org/faq/window-document-undefined
