### ISSUE TITLE
Release Notes missing

### ISSUE THREAD

**Issue by gbezyuk** [nuxt/docs#8]
Maybe it's just me becoming sorta blind (and then I'm just sorry to bother), but I can't find anything named "Release Notes" anywhere except `menu.json` file. Which means I can't translate it, which worries me a little. Could you please clarify what's going on?

**Comment by alexchopin** [comment]
Ok, that's normal don't worry about that. 
We use the Github API to fetch all release notes from there.
We'll think about a solution for translating that also, but for now I think it's ok.
You have done an amazing job!

**Comment by gbezyuk** [comment]
@alexchopin thank you twice!

**Comment by Atinux** [comment]
I don't think the release notes are worth translating them, even vue.js does not.

**Comment by gbezyuk** [comment]
Maybe you're right.
