### ISSUE TITLE
vuex: this is undefined in arrow function

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#849]
### What problem does this feature solve?

A short hint on https://nuxtjs.org/guide/vuex-store/ that `this` isn't available if you use arrow functions in file-split store modules would be nice.

Related: https://github.com/nuxt/nuxt.js/issues/4047

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c120">#c120</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @Esslamb 👋 

Yeah, that's basically it. A small remark (and maybe how to "resolve" the issue - by switching to the "normal" function declaration) should be enough ☺️

**Comment by Esslamb** [comment]
You got it @manniL on it now!
