### ISSUE TITLE
Improve `generate.dir` documentation

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#851]
### What problem does this feature solve?

Improve `generate.dir` documentation (that it is the `buildDir` for SPA/generate)

Related: https://github.com/nuxt/nuxt.js/issues/3217#issuecomment-381141531

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c123">#c123</a>)</em></sub></div>

**Comment by simson1** [comment]
Where to find generate.dir documentation ?

**Comment by manniL** [comment]
https://nuxtjs.org/api/configuration-generate#dir
