### ISSUE TITLE
Run on random free port

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#862]
### What problem does this feature solve?

Document https://twitter.com/TheAlexLichter/status/1050862540035633152

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c126">#c126</a>)</em></sub></div>

**Comment by moaxaca** [comment]
You need someone to implement this?

**Comment by christian-fei** [comment]
Hello,
I could work on it, let me know if you're interested

**Comment by manniL** [comment]
Hey @christian-fei! There is already a PR to that issue that has been merged.

If you want, you can look into [other issues](https://github.com/nuxt/docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ahacktoberfest) :relaxed: 

Thanks!
