### ISSUE TITLE
Fix source links

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#879]
After the monorepo refactor source links are off. We should point them again to the right spots. Example: [internals](https://nuxtjs.org/api/internals#nuxt-internals)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c133">#c133</a>)</em></sub></div>

**Comment by stuin** [comment]
I can get this. It looks like all of them are in the internals section? Should be pretty quick for that.
