### ISSUE TITLE
Document async nuxt.config.js

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#881]
### What problem does this feature solve?

https://github.com/nuxt/nuxt.js/pull/4021

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c134">#c134</a>)</em></sub></div>

**Comment by mornir** [comment]
Hi @manniL !
May I take this issue? Where would be the best place to add that information in the docs? 
I would put it on this page "/guide/configuration" under a new "h1" called "Asynchronous Configuration".

**Comment by manniL** [comment]
Sure @mornir 

I'd probably add a paragraph on the page (and maybe an h2) before coming to the different keys/config options.
