### ISSUE TITLE
Why are some translation directory names using Country Code instead of Language Code ?

### ISSUE THREAD

**Issue by sotayamashita** [nuxt/docs#92]
cc:/ @inouetakuya 

Why are some translation directory names using Country Code instead of Language Code? I think directory name should use language code. For example, we should choose `ja` instead of `jp` in Japanese translation. 

Thanks in advance :bow:

**Comment by sotayamashita** [comment]
I have changed title and description because it is not limited to Japanese.

**Comment by Atinux** [comment]
Hi @sotayamashita 

Indeed, we use the [href lang attribute](http://martinkura.com/list-hreflang-country-language-codes-attributes/) for the name of the folder, it seems that the Japanese should be `ja`.

@alexchopin can you change it please?

**Comment by alexchopin** [comment]
fixed

**Comment by sotayamashita** [comment]
@Atinux @alexchopin I appreciate your speedy handling :bow: :tada:
