### ISSUE TITLE
Use-case: When router.base is not default, when going to /, instead of 404, redirect to router.base as a Nuxt connect middleware example

### ISSUE THREAD

**Issue by renoirb** [nuxt/docs#984]
### What problem does this feature solve?

This is maybe an edge-case, and the point of nuxt.config.js' router.base is for when a Web server will serve Nuxt elsewhere than the domain root.

But when in local development, hitting localhost, when router.base is not / returns a 404.

### What does the proposed changes look like?

We can use that situation to document how nuxt hooks works.

**NOTE** [I have a functioning connect middleware, ][gist].  Let's add this to the docs.

[gist]: https://gist.github.com/renoirb/e201ee73e78ac80e1b7d1bc6dfec6c6f "Commented original source and canonical copy of the code embedded in this issue"

### How to use example

PS: In the [gist][gist], I've added comments.

1. Setup Nuxt config

    ```js
    // file: nuxt.config.js
    import hooks from './hooks'
    export default {
      router: {
        base: '/portal',
      },
      hooks: hooks(this),
    }
    ```

1. Hooks module setup

    ```js
    // file: hooks/index.js
    import render from './render'
    export default (nuxtConfig) => ({
      // e.g. 'render:context'
      render: render(nuxtConfig),
    })
    ```

1. Render hooks module

    ```js
    // file: hooks/render.js
    import redirectRootToPortal from './route-redirect-portal'
    export default (nuxtConfig) => {
      const router = Reflect.has(nuxtConfig, 'router') ? nuxtConfig.router : {}
      const base = Reflect.has(router, 'base') ? router.base : '/portal'
      return {
        setupMiddleware(app) {
          app.use('/', redirectRootToPortal(base))
        },
      },
    }
    ```

1. Middleware code

    ```js
    // file: hooks/route-redirect-portal.js
    import parseurl from 'parseurl'
    export default (desiredContextRoot) => function projectHooksRouteRedirectPortal(req, res, next) {
      const desiredContextRootRegExp = new RegExp(`^${desiredContextRoot}`)
      const _parsedUrl = Reflect.has(req, '_parsedUrl') ? req._parsedUrl : null
      const url = _parsedUrl !== null ? _parsedUrl : parseurl(req)
      const startsWithDesired = desiredContextRootRegExp.test(url.pathname)
      const isNotProperContextRoot = desiredContextRoot !== url.pathname
      if (isNotProperContextRoot && startsWithDesired === false) {
        const pathname = url.pathname === null ? '' : url.pathname
        const search = url.search === null ? '' : url.search
        const Location = desiredContextRoot + pathname + search
        res.writeHead(302, {
          Location,
        })
        res.end();
      }
      next()
    }
    ```

**Comment by renoirb** [comment]
Ping, I've fleshed out a complete working example. Updated here, and in the Gist.

**Comment by renoirb** [comment]
Ping @clarkdo I could include this in hare.

**Comment by clarkdo** [comment]
@renoirb Good job!

**Comment by renoirb** [comment]
Thanks for the feedback Clark.

I added you just to double check if I'm on the right track before spending time writing docs with possibly misunderstanding mistakes.

Before writing, can you confirm if you see issues in my example related to:

1. Passing `router.base` from nuxt.config.js when I'm `{hooks: hooks(this)}`.
  What about defaults and handling?
  I guess that since I already `Reflect.has()` and give an empty object, mistakenly not setting a value won't break.
  Won't that pollute/put weight into the execution stack?

1. How certain can we be about **connect**’s `http.ServerResponse`’s `_parsedUrl` property? Should I just drop the `parseurl` dependency deduplication?

Thanks for this!

**Comment by renoirb** [comment]
Work done, related to this: docs#1036
