### ISSUE TITLE
Improve Tasks on Specific Hooks in Modules Guide

### ISSUE THREAD

**Issue by hirohirodao** [nuxt/docs#997]
### Version

[2.2](https://github.com/docs/releases/tag/2.2)

### Reproduction link

[https://nuxtjs.org/guide/modules/#run-tasks-on-specific-hooks](https://nuxtjs.org/guide/modules/#run-tasks-on-specific-hooks)

### Steps to reproduce

This is Doc's issue.
Ref: https://nuxtjs.org/guide/modules/#run-tasks-on-specific-hooks

### What is expected ?

```
//before or done, ....
this.nuxt.hook('build:before', async builder => {})
//before or done, ....
this.nuxt.hook('generate:before', async generator => {})
```

### What is actually happening?

```
this.nuxt.hook('build', async builder => {})

this.nuxt.hook('generate', async generator => {})
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c144">#c144</a>)</em></sub></div>

**Comment by manniL** [comment]
Thanks for the report ☺️
